version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: deberc-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=p@ssw0rd
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - "1433:1433"
volumes:
  mssql-data: